from flask import Flask,render_template,request
import random
app=Flask(__name__)

quotes = {
    "happy": [
        "Happiness is not by chance, but by choice.",
        "Smile, it's free therapy!",
        "The most wasted of all days is one without laughter.",
        "Happiness is a warm puppy.",
        "Count your age by friends, not years. Count your life by smiles, not tears.",
        "The purpose of our lives is to be happy.",
        "Joy is the simplest form of gratitude.",
        "Happiness is when what you think, what you say, and what you do are in harmony.",
        "The only thing that will make you happy is being happy with who you are.",
        "For every minute you are angry you lose sixty seconds of happiness.",
        "Happiness depends upon ourselves.",
        "Be happy for this moment. This moment is your life.",
        "Happiness is a state of mind. It's according to the way you look at things.",
        "The secret of happiness is freedom, the secret of freedom is courage.",
        "Most folks are as happy as they make up their minds to be.",
        "Happiness is not something ready-made. It comes from your own actions.",
        "Keep your face to the sunshine and you cannot see a shadow.",
        "The power of finding beauty in the humblest things makes home happy and life lovely.",
        "Life is short, and it's up to you to make it sweet.",
        "Happiness is a direction, not a place.",
        "Every day is a new day, and you'll never be able to find happiness if you don't move on.",
        "Think of all the beauty still left around you and be happy.",
        "Happiness is having a large, loving, caring, close-knit family in another city.",
        "The best way to cheer yourself is to try to cheer someone else up.",
        "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The sunshine of the mind is the only true happiness.",
        "Don't cry because it's over, smile because it happened.",
        "Happiness grows at our own firesides, and is not to be picked in strangers' gardens.",
        "If you want to be happy, be.",
        "There is only one happiness in this life, to love and be loved.",
        "Happiness is not a goal; it's a by-product of a life well lived.",
        "The art of being happy lies in the power of extracting happiness from common objects.",
        "A smile is a curve that sets everything straight.",
        "Whatever you do, do it with all your heart.",
        "Laughter is an instant vacation.",
        "Happiness is the interval between periods of unhappiness.",
        "Focus on the powerful, euphoric, magical, adventurous, and creative possibilities.",
        "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
        "Sanity and happiness are an impossible combination.",
        "The greatest happiness you can have is knowing that you do not necessarily require happiness.",
        "Doing what you like is freedom. Liking what you do is happiness.",
        "Happiness is being content with what you have.",
        "The only joy in the world is to begin.",
        "A well-spent day brings happy sleep.",
        "Believe you can and you're halfway there.",
        "The more you praise and celebrate your life, the more there is in life to celebrate.",
        "True happiness... is not attained through self-gratification, but through fidelity to a worthy purpose.",
        "Be so happy that when others look at you, they become happy too.",
        "The roots of happiness are planted in the soil of kindness."
    ],
    "sad": [
        "It's okay to be a glow-in-the-dark person.",
        "Breathe. It's just a bad day, not a bad life.",
        "Tears are words that need to be written.",
        "Every man has his secret sorrows which the world knows not.",
        "The word 'happy' would lose its meaning if it were not balanced by sadness.",
        "Sadness flies away on the wings of time.",
        "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.",
        "To let go is to release the images and emotions, the grudges and fears of the past.",
        "Things change. And friends leave. Life doesn't stop for anybody.",
        "You cannot protect yourself from sadness without protecting yourself from happiness.",
        "The good times of today, are the sad thoughts of tomorrow.",
        "Sadness is but a wall between two gardens.",
        "Don't cry because it's over, smile because it happened.",
        "Pain is inevitable. Suffering is optional.",
        "Our sweetest songs are those that tell of saddest thought.",
        "It is both a blessing and a curse to feel everything so very deeply.",
        "Sometimes you've got to be able to listen to yourself and be okay with no one else understanding.",
        "There is no greater sorrow than to recall in misery the time when we were happy.",
        "A feeling of sadness and longing that is not akin to pain.",
        "Deep grief sometimes is almost like a specific location, a coordinate on a map of time.",
        "Every human being has a bit of sorrow in them.",
        "Sometimes, only one person is missing, and the whole world seems depopulated.",
        "What brings tears to one's eyes also brings laughter to one's heart.",
        "Life is a moderately good play with a badly written third act.",
        "It’s okay to not be okay.",
        "The soul would have no rainbow had the eyes no tears.",
        "Sadness is a guest; welcome it and let it leave when it's ready.",
        "You're not a bad person for the ways you tried to kill your sadness.",
        "Sometimes the person who tries to keep everyone happy is the most lonely person.",
        "Don’t let the shadows of yesterday spoil the sunshine of tomorrow.",
        "Behind every sweet smile, there is a bitter sadness that no one can ever see.",
        "To have felt too much is to end in feeling nothing.",
        "There are moments when I wish I could roll back the clock and make all the sadness go away.",
        "I miss the person I used to be.",
        "Crying is all right in its way while it lasts. But you have to stop sooner or later.",
        "Sadness is like a heavy blanket; sometimes you just need to sit under it for a while.",
        "The way I feel is like a puzzle with missing pieces.",
        "When you're happy, you enjoy the music but when you're sad, you understand the lyrics.",
        "You can't keep the birds of sadness from flying over your head, but you can keep them from building a nest in your hair.",
        "Winter is on my head, but eternal spring is in my heart.",
        "Grief is just love with no place to go.",
        "The walls we build around us to keep sadness out also keep out the joy.",
        "Loneliness is the human condition. No one is ever going to fill that space.",
        "We must understand that sadness is an ocean, and sometimes we drown, while other days we are forced to swim.",
        "It’s hard to forget someone who gave you so much to remember.",
        "The largest part of what we call 'personality' is determined by how we've opted to defend ourselves against anxiety and sadness.",
        "Silence is the loudest cry.",
        "You see, I usually find myself among strangers because I drift here and there trying to forget the sad things that happened to me.",
        "One day you will look back and realize that you were always enough.",
        "Sadness is a teacher, not a permanent resident.",
        "Hang in there,Better days are coming."
    ],
    "motivation": [
        "Don't stop until you're proud.",
        "Action is the foundational key to all success.",
        "The way to get started is to quit talking and begin doing.",
        "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "Don't let yesterday take up too much of today.",
        "You learn more from failure than from success. Don’t let it stop you.",
        "It’s not whether you get knocked down, it’s whether you get up.",
        "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
        "People who are crazy enough to think they can change the world, are the ones who do.",
        "Failure will never overtake me if my determination to succeed is strong enough.",
        "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneur.",
        "We may encounter many defeats but we must not be defeated.",
        "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
        "Imagine your life is perfect in every respect; what would it look like?",
        "We generate fears while we sit. We overcome them by action.",
        "Whether you think you can or think you can’t, you’re right.",
        "Security is mostly a superstition. Life is either a daring adventure or nothing.",
        "The man who has confidence in himself gains the confidence of others.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "Creativity is intelligence having fun.",
        "What you lack in talent can be made up with desire, hustle and giving 110% all the time.",
        "Do what you can with all you have, wherever you are.",
        "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
        "To see what is right and not do it is a lack of courage.",
        "A clear vision, backed by definite plans, gives you a tremendous feeling of confidence and personal power.",
        "Keep your eyes on the stars, and your feet on the ground.",
        "The only way to do great work is to love what you do.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "Your time is limited, don't waste it living someone else's life.",
        "Be yourself; everyone else is already taken.",
        "Hardships often prepare ordinary people for an extraordinary destiny.",
        "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
        "Everything you've ever wanted is on the other side of fear.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Don't watch the clock; do what it does. Keep going.",
        "It does not matter how slowly you go as long as you do not stop.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Small deeds done are better than great deeds planned.",
        "Your talent determines what you can do. Your motivation determines how much you are willing to do.",
        "Discipline is the bridge between goals and accomplishment.",
        "If you want to achieve greatness stop asking for permission.",
        "The harder the conflict, the more glorious the triumph.",
        "Opportunities don't happen. You create them.",
        "I find that the harder I work, the more luck I seem to have.",
        "Start where you are. Use what you have. Do what you can.",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "Great things never come from comfort zones.",
        "Dream it. Wish it. Do it.",
        "Success doesn't just find you. You have to go out and get it.",
        "The key to success is to focus on goals, not obstacles."
    ],
    "love": [
        "To love and be loved is to feel the sun from both sides.",
        "You are your best thing.",
        "Love is composed of a single soul inhabiting two bodies.",
        "There is no remedy for love but to love more.",
        "The best thing to hold onto in life is each other.",
        "Love isn't something you find. Love is something that finds you.",
        "I have decided to stick with love. Hate is too great a burden to bear.",
        "Where there is love there is life.",
        "Love is that condition in which the happiness of another person is essential to your own.",
        "The giving of love is an education in itself.",
        "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.",
        "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
        "Love looks not with the eyes, but with the mind.",
        "There is always some madness in love. But there is also always some reason in madness.",
        "We are shaped and fashioned by what we love.",
        "Love is a friendship set to music.",
        "The art of love is largely the art of persistence.",
        "If I know what love is, it is because of you.",
        "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
        "Life is the flower for which love is the honey.",
        "Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.",
        "Love is the only force capable of transforming an enemy into a friend.",
        "A simple 'I love you' means more than money.",
        "True love stories never have endings.",
        "Everything is clearer when you're in love.",
        "Love is like the wind, you can't see it but you can feel it.",
        "The heart has its reasons which reason knows nothing of.",
        "To love oneself is the beginning of a lifelong romance.",
        "To be brave is to love someone unconditionally, without expecting anything in return.",
        "We love because it's the only true adventure.",
        "The hunger for love is much more difficult to remove than the hunger for bread.",
        "Love makes your soul crawl out from its hiding place.",
        "The greatest thing you'll ever learn is just to love and be loved in return.",
        "Love is a canvas furnished by nature and embroidered by imagination.",
        "A heart that loves is always young.",
        "Love is an irresistible desire to be irresistibly desired.",
        "There is only one happiness in this life, to love and be loved.",
        "To love is to recognize yourself in another.",
        "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
        "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
        "Love is the magician that pulls man out of his own hat.",
        "A dream you dream alone is only a dream. A dream you dream together is reality.",
        "The beauty of love is that it can find you anywhere.",
        "Love is the poetry of the senses.",
        "Intimacy is the capacity to be rather weird with someone - and finding that that's okay with them.",
        "In the end, the love you take is equal to the love you make.",
        "Love asks me no questions, and gives me endless support.",
        "If you would be loved, love and be lovable.",
        "Spread love everywhere you go.",
        "Love is the light that never dims."
    ]
}
@app.route("/", methods=["GET","POST"])
def home():

    quote = ""
    mood = ""

    if request.method == "POST":
        mood = request.form.get("Mood")

        if mood in quotes:
            quote = random.choice(quotes[mood])

    return render_template("index.html", quote=quote, mood=mood)

@app.route("/get_quote/<mood>")
def get_quote(mood):
    if mood in quotes:
        return {"quote": random.choice(quotes[mood])}
    return {"quote": "Stay mindful!"}, 404


if __name__ == "__main__":
    app.run(debug=True)